version: '3.2'
services:
  changedetection:
    image: lucaszhang99/changedetection-undetected:latest
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - WEBDRIVER_URL=http://selenium-hub:4444/wd/hub
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - selenium-hub
      - chrome1
      - chrome2
    networks:
      - shared-network

  selenium-hub:
    image: selenium/hub:4.25.0
    container_name: browser-chrome
    hostname:  browser-chrome
    ports:
      - 4444:4444
    restart: unless-stopped
    networks:
      - shared-network

  chrome1:
    image: selenium/node-chrome:129.0
    container_name: chrome1
    hostname: chrome1
    environment:
      - SE_EVENT_BUS_HOST=browser-chrome
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    depends_on:
      - selenium-hub
    networks:
      - shared-network

  chrome2:
    image: selenium/node-chrome:129.0
    container_name: chrome2
    hostname: chrome2
    environment:
      - SE_EVENT_BUS_HOST=browser-chrome
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    depends_on:
      - selenium-hub
    networks:
      - shared-network

  chrome3:
    image: selenium/node-chrome:129.0
    container_name: chrome3
    hostname: chrome3
    environment:
      - SE_EVENT_BUS_HOST=browser-chrome
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    depends_on:
      - selenium-hub
    networks:
      - shared-network

volumes:
  changedetection-data:

networks:
  shared-network:
    driver: bridge
